---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Lab 8: cfn-init'
Parameters:
  VPC:
    Description: The default VPC
    Type: AWS::EC2::VPC::Id
    Default: vpc-c5862ab8
  Subnet:
    Description: A public subnet from default VPC.
    Type: AWS::EC2::Subnet::Id
    Default: subnet-6c65f50a
Mappings:
  RegionMap:
    us-east-1:
      Ubuntu: ami-0b6c6ebed2801a5cb
    us-east-2:
      Ubuntu: ami-06e3c045d79fd65d9

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Metadata:
      AWS::CloudFormation::Init:
        config:
          packages:
            # Install Apache2 on Ubuntu using apt package manager
            apt:
              apache2: []
          files:
            # Create the HTML file for the web server
            /var/www/html/index.html:
              content: "<html><body>Hello World!</body></html>"
              mode: '000644'
              owner: root
              group: root
          services:
            # Start and enable Apache2 service
            sysvinit:
              apache2:
                enabled: true
                ensureRunning: true
    Properties:
      ImageId: !FindInMap [RegionMap, !Ref 'AWS::Region', Ubuntu]
      InstanceType: t2.micro
      NetworkInterfaces:
      - AssociatePublicIpAddress: 'true'
        DeviceIndex: '0'
        GroupSet:
        - !Ref WebserverSecurityGroup
        SubnetId: !Ref Subnet
      Tags:
      - Key: Name
        Value: lab8-webserver
      UserData:
        'Fn::Base64': !Sub |
          #!/bin/bash -ex
          /opt/aws/bin/cfn-init -s ${AWS::StackName} -r EC2Instance --region ${AWS::Region}
  WebserverSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: lab8-webserver
      VpcId: !Ref VPC
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        FromPort: 80
        IpProtocol: tcp
        ToPort: 80
Outputs:
  WebsiteURL:
    Description: The URL pointing the webserver.
    Value: !Sub http://${EC2Instance.PublicIp}